apiVersion: v1
kind: Pod
metadata:
  name: backend
  namespace: development
  labels:
    app.kubernetes.io/name: backend
spec:
  containers:
  - name: backend
    image: clearpointacr.azurecr.io/sreassessment:backend
    ports:
      - containerPort: 80
        name: http-web-svc
        
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: development
spec:
  selector:
    app.kubernetes.io/name: backend
  ports:
  - name: backend-service-port
    protocol: TCP
    port: 8080
    targetPort: http-web-svc
        
---
apiVersion: v1
kind: Pod
metadata:
  name: frontend
  namespace: development
  labels:
    app.kubernetes.io/name: frontend
spec:
  containers:
  - name: frontend
    image: clearpointacr.azurecr.io/sreassessment:frontend
    ports:
      - containerPort: 80
        name: http-web-svc
    env:
        - name: BACKEND_HOST
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: backend_host
        - name: BACKEND_PORT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: backend_port
        
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: development
spec:
  selector:
    app.kubernetes.io/name: frontend
  ports:
  - name: frontend-service-port
    protocol: TCP
    port: 80
    targetPort: http-web-svc
        
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: development
data:
  backend_host: "BACKEND_HOST_VALUE"
  backend_port: "BACKEND_PORT_VALUE"